# test-docker-compose.yml

services:

  glpi_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: glpi_bot
    container_name: gbc
    restart: unless-stopped
    command: ["/entrypoint.sh", "test_main.py"]
    env_file: .test.env
    environment:
      - GLPI_TG_CONFIG_DIR=/configs
      - GLPI_TG_DATA_DIR=/data
    volumes:
      - "${CONFIGS_DIR}:/configs"
      - "${DATA_DIR}:/data"
